version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: mistpy/foodgram_back:v1.1
    volumes:
      - static_value:/back/backend_static/
      - media_value:/back/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: mistpy/foodgram_front:v1.1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - frontend

volumes:
  db:
  static_value:
  media_value:
