version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    #ports:
      #- "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    #environment:
      #- POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env


  backend:
    image: mistpy/foodgram_back:v1.1
#    build:
#      context: ../backend
#    restart: always
    volumes:
      - static_value:/back/backend_static/
      - media_value:/back/backend_media/
#    ports:
#      - "8000:8000"
#    expose:
#      - 8000
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: mistpy/foodgram_front:v1.1
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
#      - static_value:/usr/share/nginx/html/backend_static/:ro
#      - media_value:/usr/share/nginx/html/backend_media/:ro
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - frontend

volumes:
  db:
  static_value:
  media_value:


