# Generated by Django 3.2.14 on 2022-07-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220724_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Красный'), ('#FFA500', 'Оранжевый'), ('#FFFF00', 'Желтый'), ('#008000', 'Зеленый'), ('#0000FF', 'Синий'), ('#800080', 'Фиолетовый')], max_length=16, unique=True, verbose_name='Цвет по HEX-коду'),
        ),
    ]
